create option Privilegios INUBE
selsa-inube/iSetting-portal pull request #1
Opened 2024-07-18 15:40 UTC by SelsaErojas

create option Privilegios INUBE

2024-07-19 13:55 UTC, ANGIECATHERINEP requested changes
you need the positions icon
![image](https://github.com/user-attachments/assets/24b0fc71-06ce-482d-b7a5-2fe3ab378864)

and you needed to import the google fonts in the index.html file

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/App.tsx
> +//import AppContextProvider, { AppContext } from "@context/AppContext";
you should remove the comments

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/App.tsx
> +    //<AppContextProvider>// si lo dejo no me muestra la opción de cargos
verifying this part, when adding the appcontext, you can view privileges, that is, if it is working, you must add it

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/PageTitle/index.tsx
> +import { MdArrowBack } from "react-icons/md";
you must use the new inubekit library for these components
https://design.inube.cloud

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/feedback/LogoutModal/styles.ts
> +import styled from "styled-components";
you must use the new inubekit library for these components

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/feedback/RenderMessage/index.tsx
> +import { Stack, SectionMessage } from "@inube/design-system";
you must use the new inubekit library for these components

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/layout/AppMenu/index.tsx
> +import { Breadcrumbs, Stack } from "@inube/design-system";
you must use the new inubekit library for these components

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/layout/AppMenuGrid/index.tsx
> +import { Grid, useMediaQuery } from "@inube/design-system";
you must use the new inubekit library for these components

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/layout/AppPage/index.tsx
> +            userName={"Dora Lucia"}
this data must come from the appContext

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/components/navigation/MenuItem/index.tsx
> +import { Icon, Text, Stack, inube } from "@inube/design-system";
The inubekit library must be used for these components

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/components/GeneralInformationForm/index.tsx
> +//import { updateItemData } from "@src/mocks/utils/dataMock.service";
you must delete the comments

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/components/GeneralInformationForm/index.tsx
> +          //editDataPosition();
you must delete the comments

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on src/services/users/invitation.types.ts
> +import { IOptionInitialiceEntry } from "@src/pages/privileges/outlets/positions/add-position/types";
you must enter the alias @page

2024-07-19 13:55 UTC, ANGIECATHERINEP commented on .env
> +VITE_ICLIENT_API_URL_PERSISTENCE=http://172.106.48.22:8304/iutilities-linix-catalogos-generales-persistence-process-service/api
You should not upload this file to the repository

2024-07-22 21:56 UTC, SelsaErojas commented on src/pages/privileges/outlets/positions/components/GeneralInformationForm/index.tsx
> +
comments removed

2024-07-22 21:56 UTC, SelsaErojas commented on src/App.tsx
> +//import AppContextProvider, { AppContext } from "@context/AppContext";
comments removed, pendding new version Auth

2024-07-22 21:56 UTC, SelsaErojas commented on src/App.tsx
> +    //<AppContextProvider>// si lo dejo no me muestra la opción de cargos
pendding new version Auth

2024-07-22 21:56 UTC, SelsaErojas commented on src/components/PageTitle/index.tsx
> +import { MdArrowBack } from "react-icons/md";
ok. the change was made

2024-07-22 21:56 UTC, SelsaErojas commented on src/components/feedback/LogoutModal/styles.ts
> +import styled from "styled-components";
ok. the change was made

2024-07-22 21:57 UTC, SelsaErojas commented on src/components/feedback/RenderMessage/index.tsx
> +import { Stack, SectionMessage } from "@inube/design-system";
ok. the change was made

2024-07-22 21:57 UTC, SelsaErojas commented on src/components/layout/AppMenu/index.tsx
> +import { Breadcrumbs, Stack } from "@inube/design-system";
ok. the change was made

2024-07-22 21:57 UTC, SelsaErojas commented on src/components/layout/AppMenuGrid/index.tsx
> +import { Grid, useMediaQuery } from "@inube/design-system";
ok. the change was made

2024-07-22 21:57 UTC, SelsaErojas commented on src/components/layout/AppPage/index.tsx
> +            userName={"Dora Lucia"}
pendding new version Auth

2024-07-22 21:57 UTC, SelsaErojas commented on src/components/navigation/MenuItem/index.tsx
> +import { Icon, Text, Stack, inube } from "@inube/design-system";
ok. the change was made

2024-07-22 21:57 UTC, SelsaErojas commented on src/pages/privileges/outlets/positions/components/GeneralInformationForm/index.tsx
> +//import { updateItemData } from "@src/mocks/utils/dataMock.service";
comments removed

2024-07-22 21:57 UTC, SelsaErojas commented on src/pages/privileges/outlets/positions/components/GeneralInformationForm/index.tsx
> +          //editDataPosition();
comments removed

2024-07-22 21:57 UTC, SelsaErojas commented on src/services/users/invitation.types.ts
> +import { IOptionInitialiceEntry } from "@src/pages/privileges/outlets/positions/add-position/types";
done

2024-07-22 21:57 UTC, SelsaErojas commented on .env
> +VITE_ICLIENT_API_URL_PERSISTENCE=http://172.106.48.22:8304/iutilities-linix-catalogos-generales-persistence-process-service/api
ok. i get it

2024-07-22 23:50 UTC, ANGIECATHERINEP approved these changes

2024-07-29 19:13 UTC, Dlfp commented on src/pages/privileges/outlets/users/types/forms.types.ts
> +import { IInvitationsEntry } from "@services/users/invitation.types";
El subdirectorio /user/types y sus archivos no son necesarios en este proyecto ???

2024-07-29 19:15 UTC, Dlfp commented on src/services/users/invitation.types.ts
> +import { IOptionInitialiceEntry } from "@pages/privileges/outlets/positions/add-position/types";
El directorio /services/users y sus archivos no son necesario en este proyecto ....

2024-08-06 22:12 UTC, ANGIECATHERINEP approved these changes

2024-08-12 13:20 UTC, Dlfp approved these changes

2024-08-12 13:49 UTC, ANGIECATHERINEP approved these changes

2024-08-12 13:57 UTC, merged