Lo/set20/opcion menu principla i setting portal
selsa-inube/iSetting-portal pull request #25
Opened 2024-12-05 18:51 UTC by LinconOssa

2024-12-06 14:33 UTC, ANGIECATHERINEP approved these changes

2024-12-06 20:46 UTC, cmarin001 commented on src/components/feedback/AppCard/index.tsx
I would rather an approach like this 'import { Stack } from "@inubekit/stack";
import { Text } from "@inubekit/text";
import { Icon } from "@inubekit/icon";
import { basic } from "@design/tokens";
import { SkeletonIcon, SkeletonLine } from "@inubekit/skeleton";
import { StyledAppCard } from "./styles";

interface AppCardProps {
  description?: string;
  icon?: React.ReactNode;
  label?: string;
  url?: string;
  isLoading?: boolean;
}

function AppCard({ label, description, icon, url, isLoading }: AppCardProps) {
  if (isLoading) {
    // Render the loading state
    return (
      <StyledAppCard to={url ?? ""}>
        <Stack direction="column" gap={basic.spacing.s200}>
          <Stack width="70%">
            <SkeletonLine animated />
          </Stack>
          <Stack width="100%">
            <SkeletonLine animated />
          </Stack>
        </Stack>
        <Stack justifyContent="flex-end">
          <SkeletonIcon animated />
        </Stack>
      </StyledAppCard>
    );
  }

  // Render the loaded state
  return (
    <StyledAppCard to={url ?? ""}>
      <Stack direction="column" gap={basic.spacing.s200}>
        <Text type="title" size="medium" weight="bold">
          {label}
        </Text>
        <Text type="body" size="small">
          {description}
        </Text>
      </Stack>
      <Stack justifyContent="flex-end">
        <Icon icon={icon} appearance="dark" size="24px" cursorHover />
      </Stack>
    </StyledAppCard>
  );
}

export { AppCard };
export type { AppCardProps };
' 
Why is this better?

- Cleaner logic: You have a clear "if loading, show this block" and "else, show that block." No repeated condition checks scattered throughout.
- Easier to extend: If you need to add more elements in the future, you don’t have to wrap each in its own conditional. You just put it in the appropriate block.
- Better readability: When someone else reads the code, it's immediately clear what happens when isLoading is true vs. false.

2024-12-06 21:38 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +              {index !== businessUnits.length - 1 && <StyledHr />}
couldn't be better to use <Divider/> instead of that StyledHr?

2024-12-06 21:39 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +  z-index: 3;
why we need this z-index?

2024-12-06 21:41 UTC, cmarin001 requested changes
please check the comments

2024-12-06 21:48 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
we got the inubekit-hooks for handle the media-queries please check that approach

2024-12-06 21:48 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
same on here

2024-12-06 21:48 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
same on here

2024-12-06 22:19 UTC, cmarin001 requested changes

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/errors/ErrorNotBusinessUnit/index.tsx
> +  const { logout } = useAuth0();
It would be better to encapsulate this functionality in a custom hook that’s called after a single action, rather than scattering it across multiple places. This approach makes debugging easier and keeps the code organized. Additionally, for the onClick event, consider passing in a prop or delegating the redirection responsibility to another component. The error page should remain just that—an error page.

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/index.tsx
> +  useEffect(() => {
Why is all this logic located here? Please remember how the new structure is designed to operate.

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/index.tsx
> +  const { setBusinessUnitSigla } = useContext(AppContext);
that '  const { setBusinessUnitSigla } = useContext(AppContext);
  const [search, setSearch] = useState("");
  const [selectedBusinessUnit, setSelectedBusinessUnit] =
    useState<IBusinessUnitsPortalStaff>();
  const [businessUnitLocal, setBusinessUnitLocal] =
    useState<IBusinessUnitstate>({
      ref: null,
      value: true,
    });
  const navigate = useNavigate();

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (businessUnitLocal.ref) {
      businessUnitLocal.ref.checked = false;
    }
    setBusinessUnitLocal({ ref: null, value: true });
    setSearch(event.target.value);
  };

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setBusinessUnitLocal({ ref: event.target, value: false });
    const selectOption = businessUnits.find(
      (businessUnit0) => businessUnit0.abbreviatedName === event.target.value,
    );
    setSelectedBusinessUnit(selectOption);
  };

  const handleSubmit = () => {
    if (selectedBusinessUnit) {
      const selectJSON = JSON.stringify(selectedBusinessUnit);
      setBusinessUnitSigla(selectJSON);
    }
    navigate("/selectBusinessUnit/loading-app");
  };

  function filterBusinessUnits(
    businessUnits: IBusinessUnitsPortalStaff[],
    search: string,
  ) {
    const searchTerm = search?.toUpperCase();

    return businessUnits.filter((unit) => {
      const businessUnitName = unit?.abbreviatedName?.toUpperCase() || "";
      const businessUnitSigla = unit?.publicCode?.toUpperCase() || "";

      return (
        businessUnitName.includes(searchTerm) ||
        businessUnitSigla.includes(searchTerm)
      );
    });
  }' is too much logic for a page, it must be in a custom-hook or using a context, but please check that

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +      @media screen and (max-width: 532px) {
Take a look at this—remember, we have inubekit-hooks to handle that functionality.

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +    @media screen and (max-height: 1000px) {
Take a look at this—remember, we have inubekit-hooks to handle that functionality.

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +    @media screen and (max-width: 532px) {
Take a look at this—remember, we have inubekit-hooks to handle that functionality.

2024-12-06 22:19 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/CheckingCredentials/index.tsx
> +  const navigate = useNavigate();
```const navigate = useNavigate();
  const { appData, setBusinessUnitSigla } = useContext(AppContext);

  const selectedBusinessUnit = () => {
    const selected = businessUnits[0];
    setBusinessUnitSigla(JSON.stringify(selected));
    navigate("/selectBusinessUnit/loading-app");
  };

  const checkCredentials = useCallback(() => {
    try {
      if (!appData) {
        return;
      }

      if (appData) {
        if (!businessUnits || businessUnits.length === 0) {
          navigate("/selectBusinessUnit/error/not-related-businessUnits");
        } else if (businessUnits.length === 1) {
          selectedBusinessUnit();
        } else {
          navigate(`/selectBusinessUnit/businessUnits`);
        }
      } else {
        navigate("/selectBusinessUnit/error/not-available");
      }
    } catch (error) {
      console.info(error);
      navigate("/selectBusinessUnit/error/not-available");
    }
  }, [appData, navigate, businessUnits]);

  useEffect(() => {
    const timer = setTimeout(checkCredentials, 2000);
    return () => clearTimeout(timer);
  }, [checkCredentials]);
``` 
 that is a too much logic for a page

2024-12-06 23:56 UTC, LinconOssa commented on src/components/feedback/AppCard/index.tsx
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +              {index !== businessUnits.length - 1 && <StyledHr />}
Listos

2024-12-06 23:56 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +  z-index: 3;
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +  const { appData, businessUnitsToTheStaff, setBusinessUnitSigla } =
Listos

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
Listos

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/privileges/outlets/positions/index.tsx
>      getAll("staff-positions")
Vale si señor en la tarea 17 arregle esto

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/selectBusinessUnits/errors/ErrorNotBusinessUnit/index.tsx
> +  const { logout } = useAuth0();
Vale Gracias

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/selectBusinessUnits/index.tsx
> +  useEffect(() => {
Lo pase a un hook

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/index.tsx
> +  const { setBusinessUnitSigla } = useContext(AppContext);
Listos pase unas cosas a  un hook

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +      @media screen and (max-width: 532px) {
Listo

2024-12-06 23:56 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +    @media screen and (max-height: 1000px) {
Listo

2024-12-06 23:57 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
> +    @media screen and (max-width: 532px) {
Listo

2024-12-06 23:57 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/CheckingCredentials/index.tsx
> +  const navigate = useNavigate();
Listos

2024-12-09 16:07 UTC, cmarin001 commented on src/components/feedback/AppCard/styles.ts
> +  @media (max-width: 400px) {
We’ve integrated Inubekit-hooks to manage media queries. Please take a moment to review the implementation.

2024-12-09 16:08 UTC, cmarin001 commented on src/components/feedback/RadioBusinessUnit/styles.ts
> +  @media screen and (max-width: 532px) {
We’ve integrated Inubekit-hooks to manage media queries. Please take a moment to review the implementation.

2024-12-09 16:14 UTC, cmarin001 commented on src/components/layout/AppPage/index.tsx
>      setShowLogoutModal(!showLogoutModal);
```
  useEffect(() => {
    const selectUser = document.querySelector("header div div:nth-child(2)");
    const handleToggleuserMenu = () => {
      setShowUserMenu(!showUserMenu);
    };
```
Why are you including CSS directly in the JSX? Remember, we’re using styled-components. Please review and align with that implementation.

2024-12-09 16:26 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: BusinessUnitChangeProps) => {
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:26 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledUl = styled.ul`
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:26 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledLi = styled.li`
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:26 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainerOption = styled.div`
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:26 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledImg = styled.img`
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:28 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledHr = styled.hr`
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly. Additionally, we already have a `<Divider />` component. Are you sure we really need the `StyledHr`?

2024-12-09 16:28 UTC, cmarin001 commented on src/hooks/useBusinessUnits.ts
> +export function useBusinessUnit(businessUnits: IBusinessUnitsPortalStaff[]) {
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:30 UTC, cmarin001 commented on src/hooks/useCheckCredentials.ts
> +export default useCheckCredentials;
Why use` export default`? Remember the export structure we follow. Please align with it.

2024-12-09 16:30 UTC, cmarin001 commented on src/hooks/useClearLocalStorageOnMount.ts
> +export default useClearLocalStorageOnMount;
Why use` export default`? Remember the export structure we follow. Please align with it.

2024-12-09 16:31 UTC, cmarin001 commented on src/hooks/useSelectBusinessUnits.ts
> +export function useSelectBusinessUnits() {
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:35 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
> +interface BusinessUnitsUIProps {
It would be better just called IBusinessUnitsUI, so please adjust it

2024-12-09 16:36 UTC, cmarin001 commented on src/routes/selectBusinessunits.tsx
> +export interface IBusinessUnits {
Why are you exporting it from that location? Remember, we agreed that all exports should be placed at the end of the file. Please update accordingly.

2024-12-09 16:37 UTC, cmarin001 requested changes
please check the comments

2024-12-24 15:42 UTC, LinconOssa commented on src/components/feedback/AppCard/styles.ts
> +  @media (max-width: 400px) {
Listos

2024-12-24 15:42 UTC, LinconOssa commented on src/components/feedback/RadioBusinessUnit/styles.ts
> +  @media screen and (max-width: 532px) {
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/components/layout/AppPage/index.tsx
>      setShowLogoutModal(!showLogoutModal);
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: BusinessUnitChangeProps) => {
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainer = styled.div`
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledUl = styled.ul`
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledLi = styled.li`
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainerOption = styled.div`
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/hooks/useBusinessUnits.ts
> +export function useBusinessUnit(businessUnits: IBusinessUnitsPortalStaff[]) {
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/hooks/useCheckCredentials.ts
> +export default useCheckCredentials;
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/hooks/useHomeLogic.ts
> +export default useHomeLogic;
Listos

2024-12-24 15:43 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
> +interface BusinessUnitsUIProps {
Listos

2024-12-30 22:21 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
>  interface StyledBusinessUnitsListProps {
It would be better to name it `IStyledBusinessUnitsList` instead of `StyledBusinessUnitsListProps` to maintain consistency

2024-12-30 22:23 UTC, cmarin001 commented on src/pages/home/interface.tsx
It would be better to name it `IHome` instead of `HomeProps` to maintain consistency alsothis 'const renderLogo = (imgUrl: string) => {
  return (
    <StyledContentImg to="/">
      <StyledLogo src={imgUrl} />
    </StyledContentImg>
  );
};' must be on another file in order to mantain as clean as possible

2024-12-30 22:29 UTC, cmarin001 requested changes
check the comments

2024-12-30 22:29 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
```
function NoResultsMessage({ search }: { search: string }) {
  return (
    <StyledNoResults>
      <Text size="medium">
        No se encontraron resultados para &quot;{search}&quot;.
      </Text>
      <Text size="medium">
        Por favor, intenta modificando los parámetros de búsqueda.
      </Text>
    </StyledNoResults>
  );
}
```
That must be on another file in order to mantain as clean as possible

2024-12-30 23:26 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/styles.ts
>  interface StyledBusinessUnitsListProps {
Ready

2024-12-30 23:26 UTC, LinconOssa commented on src/pages/home/interface.tsx
Ready

2024-12-30 23:26 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
Ready

2024-12-31 15:59 UTC, cmarin001 commented on src/hooks/noResultsMessage/useNoResultsMessage.tsx
> +interface NoResultsMessageProps {
It would be better to name it `INoResultsMessage` instead of `NoResultsMessageProps` to maintain consistency

2024-12-31 16:05 UTC, cmarin001 commented on src/hooks/noResultsMessage/useNoResultsMessage.tsx
> +function NoResultsMessage({ search }: NoResultsMessageProps) {
Why are some components and pages defined as functions while others are declared as constants?

What’s the Actual Difference?
Syntax / Readability

Some developers prefer the arrow-function style for consistency (especially if using hooks heavily or writing lots of inline callbacks).
Others prefer named function declarations for clarity or for showing a function’s name in debugging stacks.
Named vs. Anonymous Functions

With arrow functions assigned to a variable, the function itself is anonymous (though the variable name will often appear in stack traces).
With a named function, the function’s name (NoResultsMessage) is more directly tied to the function itself, which can improve stack trace readability.
Hoisting

Named function declarations are hoisted, meaning they are accessible before their definition in the file (though in React files, this is rarely a deciding factor).
Arrow functions assigned to variables are not hoisted in the same way.
Destructuring Location

In the arrow-function version, you could destructure directly in the parameter as well, but you opted to destructure inside the function body.
In the named function version, you destructure in the function signature.
Performance

In modern React and bundlers, there is effectively no noticeable performance difference between these two patterns. It’s primarily a stylistic choice.

2024-12-31 16:05 UTC, cmarin001 commented on src/pages/home/interface.tsx
> +function HomeUI(props: IHome) {
Why are some components and pages defined as functions while others are declared as constants?

2024-12-31 16:05 UTC, cmarin001 commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
>  function BusinessUnitsUI({
Why are some components and pages defined as functions while others are declared as constants?

2024-12-31 16:05 UTC, cmarin001 requested changes
please check the comments

2024-12-31 16:59 UTC, LinconOssa commented on src/hooks/noResultsMessage/useNoResultsMessage.tsx
> +function NoResultsMessage({ search }: NoResultsMessageProps) {
It will be done in a separate task

2024-12-31 16:59 UTC, LinconOssa commented on src/hooks/noResultsMessage/useNoResultsMessage.tsx
> +interface NoResultsMessageProps {
Ready

2024-12-31 16:59 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +function HomeUI(props: IHome) {
It will be done in a separate task

2024-12-31 16:59 UTC, LinconOssa commented on src/pages/selectBusinessUnits/outlets/BusinessUnit/interface.tsx
>  function BusinessUnitsUI({
It will be done in a separate task

2025-01-02 20:33 UTC, cmarin001 approved these changes
meet the requirements

2025-01-02 20:33 UTC, merged