Lo/set17/integrate backend service of positions
selsa-inube/iSetting-portal pull request #26
Opened 2024-12-06 22:36 UTC by LinconOssa

2024-12-09 16:39 UTC, cmarin001 commented on src/components/data/Title/index.tsx
> +interface TitleProps {
It would be better that be called ITitle, so please adjust it

2024-12-09 16:39 UTC, cmarin001 commented on src/components/feedback/AppCard/index.tsx
> +interface AppCardProps {
It would be better that be called IAppCard, so please adjust it

2024-12-09 16:41 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +interface BusinessUnitChangeProps {
It would be better that be called IBusinessUnitChange, so please adjust it

2024-12-09 16:43 UTC, cmarin001 commented on src/pages/home/interface.tsx
> +interface HomeProps {
It would be better just called like IHome, please adjust it

2024-12-09 16:44 UTC, cmarin001 requested changes
check the comments

2024-12-24 17:06 UTC, LinconOssa commented on src/components/data/Title/index.tsx
> +interface TitleProps {
listos

2024-12-24 17:06 UTC, LinconOssa commented on src/components/feedback/AppCard/index.tsx
> +interface AppCardProps {
listos

2024-12-24 17:06 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +interface BusinessUnitChangeProps {
listos

2024-12-24 17:06 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +interface HomeProps {
listos

2024-12-30 20:39 UTC, cmarin001 commented on src/components/feedback/AppCard/index.tsx
that implementation is not clean, not scalable so please chech this one 

import { Stack } from "@inubekit/stack";
import { Text } from "@inubekit/text";
import { Icon } from "@inubekit/icon";
import { tokens } from "@design/tokens";
import { SkeletonIcon, SkeletonLine } from "@inubekit/skeleton";
import { StyledAppCard } from "./styles";
import { useMediaQuery } from "@inubekit/hooks";

interface IAppCard {
  description?: string;
  icon?: React.ReactNode;
  label?: string;
  url?: string;
  isLoading?: boolean;
}

function AppCard({ label, description, icon, url, isLoading }: IAppCard) {
  const screenMobile = useMediaQuery("(max-width: 400px)");
  if (isLoading) {
    return (
      <StyledAppCard to={url ?? ""} $isMobile={screenMobile}>
        <Stack direction="column" gap={tokens.spacing.s200}>
          <Stack width="70%">
            <SkeletonLine animated />
          </Stack>
          <Stack width="100%">
            <SkeletonLine animated />
          </Stack>
        </Stack>
        <Stack justifyContent="flex-end">
          <SkeletonIcon animated />
        </Stack>
      </StyledAppCard>
    );
  }
  return (
    <StyledAppCard to={url ?? ""} $isMobile={screenMobile}>
      <Stack direction="column" gap={tokens.spacing.s200}>
        <Text type="title" size="medium" weight="bold">
          {label}
        </Text>
        <Text type="body" size="small">
          {description}
        </Text>
      </Stack>
      <Stack justifyContent="flex-end">
        <Icon icon={icon} appearance="dark" size="24px" cursorHover />
      </Stack>
    </StyledAppCard>
  );
}

export { AppCard };
export type { IAppCard };

so it can be better

2024-12-30 20:41 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: IBusinessUnitChange) => {
To maintain consistency, that export must be placed at the end of the file

2024-12-30 20:42 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +interface IBusinessUnitChange {
that interface must be exported as well

2024-12-30 20:45 UTC, cmarin001 commented on src/pages/home/interface.tsx
> +function HomeUI(props: IHome) {
```
  const [collapse, setCollapse] = useState(false);
  const [selectedClient, setSelectedClient] = useState<string>("");
  const collapseMenuRef = useRef<HTMLDivElement>(null);
  const businessUnitChangeRef = useRef<HTMLDivElement>(null);
  const isTablet = useMediaQuery("(max-width: 944px)");
  const username = appData.user.userName.split(" ")[0];
  useEffect(() => {
    if (appData.businessUnit.publicCode) {
      setSelectedClient(appData.businessUnit.abbreviatedName);
    }
  }, [appData]);
  const handleLogoClick = (businessUnit: IBusinessUnitsPortalStaff) => {
    const selectJSON = JSON.stringify(businessUnit);
    setBusinessUnitSigla(selectJSON);
    setSelectedClient(businessUnit.abbreviatedName);
    setCollapse(false);
  };
```
"That is an excessive amount of code for a page, and it's even more problematic to place it in an interface meant solely for layout. Ideally, the logic should be moved to a custom hook, leaving the code on the page concise and focused

2024-12-30 20:46 UTC, cmarin001 requested changes
please check comments

2024-12-30 21:31 UTC, LinconOssa commented on src/components/feedback/AppCard/index.tsx
Listos

2024-12-30 21:31 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: IBusinessUnitChange) => {
Listos

2024-12-30 21:31 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +interface IBusinessUnitChange {
Listos

2024-12-30 21:31 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +function HomeUI(props: IHome) {
Listos

2024-12-30 22:13 UTC, cmarin001 commented on src/hooks/useBusinessUnitState.ts
> +export const useHomeLogic = () => {
Exports should be placed at the end of the file in a single, unified line

2024-12-30 22:14 UTC, cmarin001 requested changes
please check the comments

2024-12-30 22:38 UTC, LinconOssa commented on src/hooks/useBusinessUnitState.ts
> +export const useHomeLogic = () => {
Ready

2024-12-31 16:49 UTC, cmarin001 approved these changes
meet the requirements

2024-12-31 16:49 UTC, merged