Lo/set28/assisted and first step
selsa-inube/iSetting-portal pull request #27
Opened 2024-12-30 17:20 UTC by LinconOssa

En esta tarjeta se la tarea 39 40 y 41

2024-12-30 20:50 UTC, cmarin001 commented on src/components/SelectCheck/OptionItem/index.tsx
> +interface IOptionItemCheckedProps {
It would be better to name it `IOptionItemChecked` instead of `IOptionItemCheckedProps` to maintain consistency

2024-12-30 20:51 UTC, cmarin001 commented on src/components/SelectCheck/OptionList/index.tsx
> +interface OptionListProps {
It would be better to name it `IOptionList` instead of `IOptionListProps` to maintain consistency

2024-12-30 20:53 UTC, cmarin001 commented on src/components/SelectCheck/index.tsx
> +interface SelectCheckProps {
It would be better to name it `ISelectCheck` instead of `SelectCheckProps` to maintain consistency

2024-12-30 20:54 UTC, cmarin001 commented on src/components/SelectCheck/interface.tsx
> +interface SelectCheckUIProps extends SelectCheckProps {
It would be better to name it `ISelectCheckUI` instead of `SelectCheckUIProps` to maintain consistency

2024-12-30 20:57 UTC, cmarin001 commented on src/components/SelectCheck/styles.ts
> +    if (disabled) {
```
   if (disabled) {
      return (
        (theme?.palette?.neutral?.N20 || inube.palette.neutral.N20) +
        "; pointer-events: none; opacity: 0.5;"
      );
    }
    if ($focused && !$readonly) {
      return theme?.palette?.blue?.B300 || inube.palette.blue.B300;
    }
    if ($status === "invalid" && !$readonly) {
      return theme?.palette?.red?.R400 || inube.palette.red.R400;
    }
    return theme?.palette?.neutral?.N40 || inube.palette.neutral.N40;
```
That is too much logic for a styles sheet

2024-12-30 20:58 UTC, cmarin001 commented on src/components/SelectCheck/styles.ts
> +  color: ${({ theme, disabled }) => {
That is too much logic for a styles sheet

2024-12-30 21:01 UTC, cmarin001 commented on src/components/feedback/AppCard/styles.ts
> +  @media (max-width: 400px) {
That statement should not be used there; instead, the idea is to utilize inubekit-hooks

2024-12-30 21:06 UTC, cmarin001 commented on src/components/menu/MenuLink/index.tsx
> +interface MenuLinkprops {
It would be better to name it `IMenuLink` instead of `MenuLinkprops` to maintain consistency

2024-12-30 21:10 UTC, cmarin001 commented on src/components/menu/MenuOption/index.tsx
> +interface MenuOptionProps {
It would be better to name it `IMenuOption` instead of `MenuOptionProps` to maintain consistency

2024-12-30 21:10 UTC, cmarin001 commented on src/components/menu/MultipleChoices/index.tsx
> +interface IMultipleChoicesProps {
It would be better to name it `IIMultipleChoices` instead of `IMultipleChoicesProps` to maintain consistency

2024-12-30 21:13 UTC, cmarin001 commented on src/components/menu/MultipleChoices/styles.ts
> +export const StyledContainer = styled.div`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:13 UTC, cmarin001 commented on src/components/menu/MultipleChoices/styles.ts
> +export const StyledSelection = styled.div`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:14 UTC, cmarin001 commented on src/components/menu/index.tsx
> +interface MenuProps {
It would be better to name it `IMenuProps` instead of `MenuProps` to maintain consistency

2024-12-30 21:15 UTC, cmarin001 commented on src/components/submit/FormButtons/index.tsx
> +interface IFormButtonsProps {
It would be better to name it `IFormButtons` instead of `IFormButtonsProps` to maintain consistency

2024-12-30 21:16 UTC, cmarin001 commented on src/components/templates/AssignmentForm/index.tsx
> +interface AssignmentFormProps {
It would be better to name it `IAssignmentForm` instead of `AssignmentFormProps` to maintain consistency

2024-12-30 21:18 UTC, cmarin001 commented on src/components/templates/AssignmentForm/index.tsx
> +  const menuOptions: IOption[] = [
that mock must be not part of the component

2024-12-30 21:25 UTC, cmarin001 commented on src/components/templates/AssignmentForm/index.tsx
> +    const newFilteredEntries = filteredRows.map((entry) => ({
```

  const handleToggleAllEntries = (allocate: boolean) => {
    const newFilteredEntries = filteredRows.map((entry) => ({
      ...entry,
      isActive: allocate,
    }));

    const newEntries = entries.map((entry) => {
      const filteredEntry = newFilteredEntries.find((e) => e.id === entry.id);
      return filteredEntry ? filteredEntry : entry;
    });

    setIsAssignAll(allocate);
    handleChange(newEntries);
    setFilteredRows(newFilteredEntries);
  };

  const handleToggleEntry = (id: string) => {
    const newEntries = entries.map((entry) => {
      if (entry.id === id) {
        const updatedEntry = {
          ...entry,
          isActive: !entry.isActive,
        };

        if (updatedEntry.isActive !== entry.isActive) {
          const updatedChangedData = [
            ...changeData.filter((e) => e.id !== entry.id),
            updatedEntry,
          ];
          setChangedData(updatedChangedData);
        }

        return updatedEntry;
      }

      return entry;
    });

    handleChange(newEntries);
  };

  const handleFilter = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFilter(e.target.value);
  };

  const handleToggleMenuInvitation = () => {
    setShowMenu((prevShowMenu) => !prevShowMenu);
  };

  const handleCloseMenuInvitation = () => {
    setShowMenu(false);
  };

  const options: Option[] = valueSelect.map((entry) => ({
    id: entry.k_uso,
    label: entry.n_uso,
    checked: selectedOptions.includes(entry.k_uso),
  }));

  const handleSelectChange = (options: IOptionItemCheckedProps[]) => {
    const selectedIds = options
      .filter((option) => option.checked)
      .map((option) => option.id);
    setSelectedOptions(selectedIds);
  };

  useEffect(() => {
    if (selectedOptions.length === 0 && filterValue.length === 0) {
      setFilteredRows(entries);
      return;
    }
    let newfilter = filteredRows;

    if (selectedOptions.length > 0) {
      newfilter = entries.filter(
        (entry) => entry.k_uso && selectedOptions.includes(entry.k_uso)
      );
    }

    if (filterValue.length > 0) {
      newfilter = newfilter.filter(
        (entry) =>
          entry.value.toLowerCase().includes(filterValue.toLowerCase()) ||
          (entry.n_uso ?? "").toLowerCase().includes(filterValue.toLowerCase())
      );
    }
    setFilteredRows(newfilter);
  }, [selectedOptions, filterValue]);

  const handleFilterInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFilterValue(e.target.value);
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };

  const onHandleSelectCheckChange = (id: string) => {
    setFilteredRows((prevRows) =>
      prevRows.map((entry) =>
        entry.id === id
          ? {
              ...entry,
              isActive: !entry.isActive,
            }
          : entry
      )
    );
    handleToggleEntry(id);
  };
```
That implementation works; however, it involves a significant amount of code that, upon closer consideration, should not be part of the component. Instead, it should be the responsibility of whoever implements it

2024-12-30 21:26 UTC, cmarin001 commented on src/components/templates/AssignmentForm/interface.tsx
> +interface AssignmentFormUIProps {
It would be better to name it `IAssignmentFormUI` instead of `AssignmentFormUIProps` to maintain consistency

2024-12-30 21:31 UTC, cmarin001 commented on src/components/templates/AssignmentForm/interface.tsx
I'm uncertain about this component—what do you think? While the code likely works as intended, are we confident that all of this should be part of a single component? Wouldn't it be better to design it in a way that makes it more scalable, with responsibilities more clearly defined?

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: IBusinessUnitChange) => {
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainer = styled.div`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledUl = styled.ul`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledLi = styled.li`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainerOption = styled.div`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledImg = styled.img`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:33 UTC, cmarin001 commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledHr = styled.hr`
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:37 UTC, cmarin001 commented on src/hooks/useAuthRedirect.ts
> +        initializeDataDB();
```
    if (hasRedirected) return;
    if (portalPublicCode.abbreviatedName) {
      if (businessManagersData && !isLoading && !isAuthenticated) {
        loginWithRedirect();
        initializeDataDB();
      } else if (isAuthenticated) {
        setHasRedirected(true);
      } else {
        setHasError(true);
      }
    } else {
      setHasError(true);
    }
```

That implementation contains too many if-statements, which could increase cyclomatic complexity and potentially result in code smells. Please review the implementation and consider a more efficient alternative. Here's a resource for reference: [Cyclomatic Complexity](https://brainhub.eu/library/measuring-cyclomatic-complexity)

2024-12-30 21:38 UTC, cmarin001 commented on src/mocks/utils/dataMock.service.ts
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:39 UTC, cmarin001 commented on src/pages/home/interface.tsx
> +  const { data } = props;
```
const { data } = props;

  const { appData, businessUnitsToTheStaff, setBusinessUnitSigla } =
    useContext(AppContext);
  const [collapse, setCollapse] = useState(false);
  const [selectedClient, setSelectedClient] = useState<string>("");

  const collapseMenuRef = useRef<HTMLDivElement>(null);
  const businessUnitChangeRef = useRef<HTMLDivElement>(null);
  const isTablet = useMediaQuery("(max-width: 944px)");
  const username = appData.user.userName.split(" ")[0];

  useEffect(() => {
    if (appData.businessUnit.publicCode) {
      setSelectedClient(appData.businessUnit.abbreviatedName);
    }
  }, [appData]);

  const handleLogoClick = (businessUnit: IBusinessUnitsPortalStaff) => {
    const selectJSON = JSON.stringify(businessUnit);
    setBusinessUnitSigla(selectJSON);
    setSelectedClient(businessUnit.abbreviatedName);
    setCollapse(false);
  };
```
That is an excessive amount of code for a page, and it's even more problematic to place it in an interface meant solely for layout. Ideally, the logic should be moved to a custom hook, leaving the code on the page concise and focused

2024-12-30 21:40 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
That statement should not be used there; instead, the idea is to utilize inubekit/hooks

2024-12-30 21:40 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
That statement should not be used there; instead, the idea is to utilize inubekit/hooks

2024-12-30 21:40 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
That statement should not be used there; instead, the idea is to utilize inubekit/hooks

2024-12-30 21:41 UTC, cmarin001 commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
That statement should not be used there; instead, the idea is to utilize inubekit/hooks

2024-12-30 21:45 UTC, cmarin001 commented on src/pages/privileges/outlets/positions/config/dataPositions.tsx
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:45 UTC, cmarin001 commented on src/pages/privileges/outlets/positions/index.tsx
>  export function Positions() {
Exports should be placed at the end of the file in a single, unified line

2024-12-30 21:58 UTC, cmarin001 commented on src/pages/privileges/outlets/positions/interface.tsx
>  interface IPositionsProps {
It would be better to name it `IPositions` instead of `IPositionsProps` to maintain consistency

2024-12-30 22:05 UTC, cmarin001 commented on src/pages/privileges/outlets/positions/interface.tsx
Exports should be placed at the end of the file in a single, unified line

2024-12-30 22:10 UTC, cmarin001 requested changes
please check the comments

2024-12-30 22:30 UTC, LinconOssa commented on src/components/SelectCheck/OptionItem/index.tsx
> +interface IOptionItemCheckedProps {
Ready

2024-12-30 22:30 UTC, LinconOssa commented on src/components/SelectCheck/OptionList/index.tsx
> +interface OptionListProps {
Ready

2024-12-30 22:30 UTC, LinconOssa commented on src/components/SelectCheck/interface.tsx
> +interface SelectCheckUIProps extends SelectCheckProps {
Ready

2024-12-30 22:30 UTC, LinconOssa commented on src/components/SelectCheck/styles.ts
> +    if (disabled) {
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/SelectCheck/styles.ts
> +  color: ${({ theme, disabled }) => {
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/feedback/AppCard/styles.ts
> +  @media (max-width: 400px) {
This has already been fixed in task set20:
![image](https://github.com/user-attachments/assets/3c710539-4d68-44e7-8aae-6cd48615bbb2)

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/MenuLink/index.tsx
> +interface MenuLinkprops {
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/MenuOption/index.tsx
> +interface MenuOptionProps {
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/MultipleChoices/index.tsx
> +interface IMultipleChoicesProps {
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/MultipleChoices/styles.ts
> +export const StyledContainer = styled.div`
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/MultipleChoices/styles.ts
> +export const StyledSelection = styled.div`
Ready

2024-12-31 16:40 UTC, LinconOssa commented on src/components/menu/index.tsx
> +interface MenuProps {
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/submit/FormButtons/index.tsx
> +interface IFormButtonsProps {
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/templates/AssignmentForm/index.tsx
> +interface AssignmentFormProps {
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/templates/AssignmentForm/index.tsx
> +  const menuOptions: IOption[] = [
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/templates/AssignmentForm/index.tsx
> +    const newFilteredEntries = filteredRows.map((entry) => ({
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/templates/AssignmentForm/interface.tsx
> +interface AssignmentFormUIProps {
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/components/templates/AssignmentForm/interface.tsx
I would recommend that the current approach might not be the most scalable in the long term. While the code likely works as intended, combining all the logic—like handling form submission, search functionality, filtering, and toggling—into a single component can lead to a "God component" that becomes difficult to maintain and extend.

It would be better to break it down into smaller, more focused components. For instance, you could have separate components for:

Search and filter logic
Toggle handling (perhaps even a separate Toggle component or a container for the toggle functionality)
Table for displaying rows
Actions (assigning/desassigning)
This would make the components more reusable, easier to test, and allow you to follow the Single Responsibility Principle. It would also make it easier to scale and modify the behavior of each piece without affecting the entire structure.

So, while it might work now, it's usually better to consider a more modular approach to ensure maintainability and future scalability.

If so, we can do this in a separate task so as not to extend the task.

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/index.tsx
> +export const BusinessUnitChange = (props: IBusinessUnitChange) => {
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainer = styled.div`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledUl = styled.ul`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledLi = styled.li`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledContainerOption = styled.div`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledImg = styled.img`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/design/inputs/BusinessUnitChange/styles.ts
> +export const StyledHr = styled.hr`
I already made this change in the set20 task:

![image](https://github.com/user-attachments/assets/1075c4ca-f427-4cc5-8ad4-cdeda5936d3f)

2024-12-31 16:41 UTC, LinconOssa commented on src/hooks/useAuthRedirect.ts
> +        initializeDataDB();
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/mocks/utils/dataMock.service.ts
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/pages/home/interface.tsx
> +  const { data } = props;
Ready

2024-12-31 16:41 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
It has already been fixed in the set20 activity

2024-12-31 16:41 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
It has already been fixed in the set20 activity

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 805px) {
It has already been fixed in the set20 activity

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/home/styles.ts
> +  @media screen and (max-width: 532px) {
It has already been fixed in the set20 activity

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/privileges/outlets/positions/config/dataPositions.tsx
Ready

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/privileges/outlets/positions/index.tsx
>  export function Positions() {
Ready

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/privileges/outlets/positions/interface.tsx
>  interface IPositionsProps {
Ready

2024-12-31 16:42 UTC, LinconOssa commented on src/pages/privileges/outlets/positions/interface.tsx
Ready

2025-01-02 15:23 UTC, cmarin001 approved these changes
meet the requirements

2025-01-02 15:24 UTC, merged