Create the single choice component
selsa-inube/iSetting-portal pull request #3
Opened 2024-08-01 17:34 UTC by diegoAndres01

Create the single choice component

2024-08-02 15:32 UTC, Andresbl123 approved these changes

2024-08-02 15:32 UTC, Andresbl123 commented on src/components/layout/SingleChoice/stories/SingleChoice.stories.tsx
Como recomendación, para solucionar el error en la historia del componte appPege, y el error de de la tipografía en el contenido del `input`, es de crear dos archivos en el directorio `.storybook`,  `preview-head.html` : `<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
  rel="stylesheet"
/>` y   `preview-body.html` : `<div id="portals"></div>`

2024-08-07 22:48 UTC, carin91 requested changes

2024-08-07 22:48 UTC, carin91 commented on package-lock.json
> -    "node_modules/@esbuild/aix-ppc64": {
Why do you delete this dependency? i'm unable to run storybook due to the lack of this dependency.

2024-08-14 04:10 UTC, carin91 requested changes

2024-08-14 04:10 UTC, carin91 commented on .env
> -VITE_USERS_URI=http://localhost:3000/privileges/users
Please do not delete the .env, i will talk with Dora Lucia to solve this issue.

2024-08-14 04:10 UTC, carin91 commented on src/components/inputs/SingleChoice/index.tsx
> +        <Toggle
I would create a new component to wrap the others (single choice, multiple choice and so on)

2024-08-16 03:02 UTC, carin91 approved these changes

2024-08-16 03:02 UTC, carin91 commented on src/components/inputs/SingleChoice/index.tsx
> +        required,
avoid the coercion using required=false

2024-08-16 03:02 UTC, merged