Create the from to component
selsa-inube/iSetting-portal pull request #4
Opened 2024-08-05 14:20 UTC by diegoAndres01

Create the from to component 
Card Jira 
https://inube.atlassian.net/browse/CB-120

2024-08-06 15:07 UTC, Andresbl123 commented on src/components/feedback/InputRange/index.tsx
> +        <>
creo que aquí podemos usar un contenedor, esto permitiría poder ajustar temas de layout y responsive, ya que ahora están dejando de algunos espacios que lo rompen 
![image](https://github.com/user-attachments/assets/b93339c3-5ab3-4e20-975e-268b1e7e665a)

2024-08-08 13:55 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-08-14 04:16 UTC, carin91 requested changes

2024-08-14 04:16 UTC, carin91 commented on src/components/feedback/InputRange/index.tsx
> +    checked?: boolean;
Relocate the optional props and the bottom

2024-08-14 04:16 UTC, carin91 commented on src/components/feedback/InputRange/index.tsx
> +    typeInput: ITextfieldInputType;
Relocate the mandatory props at the top

2024-08-14 04:16 UTC, carin91 commented on src/components/feedback/InputRange/index.tsx
> +            <Toggle
i would create a new Toggle component to wrap the others

2024-08-14 04:16 UTC, carin91 commented on src/components/feedback/InputRange/index.tsx
> +                                <Datefield
Despite the wireframes, the "from" "to" component is not for dates.
Could be money or a general number.
As an example "Antiguedad de 5 años a 10 años"
"Desembolso de $10'000.000 a $20'000.000"
i would include a prop to evaluate whether is money or not.

2024-08-14 04:16 UTC, carin91 commented on src/components/feedback/InputRange/index.tsx
> +                                label="Desde"
The label should be rendered from a config file, not a magical word.

2024-08-16 03:07 UTC, carin91 approved these changes

2024-08-16 03:07 UTC, carin91 commented on src/components/feedback/InputRange/stories/InputRange.stories.tsx
> +  title: "components/InputRange",
Relocate the story to "components/inputs/inputRange"
![image](https://github.com/user-attachments/assets/96f666b1-dc2b-43ee-b6ac-99604d1d9440)

2024-08-20 12:52 UTC, merged